name: flutter_google_books_corsov2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  dio: ^5.7.0
  logger: ^2.4.0
  flutter_bloc: ^8.1.6
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  json_theme: ^6.5.3+4
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  json_serializable: ^6.8.0



flutter:
  uses-material-design: true
  assets:
    - assets/theme/theme.json